name: CI

on: [pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore BARS-Client-V2.sln

      - name: Build
        run: dotnet build BARS-Client-V2.sln --configuration Release --no-restore
